### ISSUE TITLE
Django 1.9.6 support for templates and html tags

### ISSUE THREAD

**Issue by enmanuelmartinez** [koleror/django-admin-views#25]
-First Django is not using TEMPLATE_DIRS anymore its using the fallowing structure

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG
        },
    },
]

-Second if we use template_dirs like legacy code the application install the admin index for django-admin-views but its present all html in the top of app module.
I did the example in the documentation and show the fallowing Html.

<tr> <th scope="row"> <img src="/static/admin_views/icons/view.png" alt="Custom admin view 'Process This'" /> <a href="/admin/products/category/process">Process This</a></th> <td>&nbsp;</td> <td>&nbsp;</td> </tr> <tr> <th scope="row"> <img src="/static/admin_views/icons/link.png" alt="Link to 'Go to LJW'" /> <a href="http://www.ljworld.com">Go to LJW</a></th> <td>&nbsp;</td> <td>&nbsp;</td> </tr>

**Comment by unruthless** [comment]
@enmanuelmartinez Your screen shots aren't showing up for me, but if I understand you correctly, you're seeing literal HTML being rendered to the screen, something like this:

![screen shot 2016-05-26 at 12 19 17 pm](https://cloud.githubusercontent.com/assets/142906/15595420/d25c25f0-2373-11e6-87ac-176d334cc498.png)

The above is a screenshot I took of my app after updating from django v1.8.13 to v1.9.6, while running  `django-admin-views` v0.5.0.

Updating to `django-admin-views` v0.7.0 solved this problem for me.

**Comment by koleror** [comment]
Django 1.9 is no longer supported as deprecated by django. So closing the issue
