### ISSUE TITLE
Django 2.0 support?

### ISSUE THREAD

**Issue by gabn88** [koleror/django-admin-views#34]
Hi @frankwiles,

Just wondering if you are planning to support Django 2.0 with this package? 

We are using your project for one or two extra buttons in the admin and it would be cool to keep them after we upgraded to Django 2.0. I have no idea of the time involved with creating support for Django 2.0, and I know everybody has too less time these days. Therefore a yes/no for Django 2.0 support would already be a great answer :)

Thank you!

**Comment by frankwiles** [comment]
Sadly we haven't used this with a client in a really long time so, I'd be happy to take and merge a PR or turn this over to a good steward for the project.  But it will probably be a long time before I find some spare time to work on it myself.

**Comment by akx** [comment]
`django-admin-views` seems to work with Django 2.0 right out of the box 🎉 

![screen shot 2018-07-17 at 11 16 48](https://user-images.githubusercontent.com/58669/42804937-10b72c8a-89b3-11e8-9bd1-f9a3c3729880.png)

**Comment by frankwiles** [comment]
Really wow? That's surprising!

**Comment by koleror** [comment]
Hey there! 

I'm glad that it worked with django 2 out of the box. However, it doesn't with Django 3. 
I'd be happy to take over this project if you wish.

**Comment by gabn88** [comment]
@frankwiles Sadly there is no Django 3 support. Would you be willing to let this project be taken over? I'm now using a fork from @tyilo .

**Comment by frankwiles** [comment]
Sure @koleror @gabn88 or @tyilo is any (or all of you) want to take it over that's fine with me.  We haven't had a client use this in a long time and haven't been able to devote any time to maintaining it.

**Comment by tyilo** [comment]
I already created a PR almost 3 years ago: https://github.com/frankwiles/django-admin-views/pull/35

**Comment by koleror** [comment]
I would happily take this over.

**Comment by frankwiles** [comment]
Sounds like a plan @koleror I'll send you an email about details I need to transfer it to you.

**Comment by gabn88** [comment]
@tyilo @koleror thank you for responding and stepping in. Much appreciated.

**Comment by frankwiles** [comment]
Just to keep everyone in the loop, we've started the transfer process.  Should be done in the day next or so.

**Comment by koleror** [comment]
I'm now the new owner of this project. 
I'll update it soon, but would happily accept pull requests in the meantime if you want.

**Comment by koleror** [comment]
The project now supports django 3 and 4. Closing the issue!
